version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: always

    ports:
      - "1883:1883"   # MQTT TCP (necesario para ESP32)
      - "9001:9001"   # WebSockets (opcional)

    volumes:
      - ../files/config:/mosquitto/config
      - ../files/data:/mosquitto/data
      - ../files/log:/mosquitto/log