version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: postgres_autoscore
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"  # Puerto externo 5433 para evitar conflictos con Dokploy
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      autoscore_net:
        ipv4_address: 172.19.0.2
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  api_risk:
    build: ./Apis/risk_score
    container_name: api_risk_score
    environment:
      URL_API_ZIDRA: ${URL_API_ZIDRA}
      USUARIO_ZIDRA: ${USUARIO_ZIDRA}
      PASSWORD_ZIDRA: ${PASSWORD_ZIDRA}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB_AUTOSCORE}
    volumes:
      - api_risk_data:/app/data
      - api_risk_models:/app/models
      - api_risk_reports:/app/reports
      - api_risk_files:/app/files
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - autoscore_net
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api_risk.rule=Host(`api-risk.rdev7.net.pe`)"
      - "traefik.http.routers.api_risk.entrypoints=websecure"
      - "traefik.http.routers.api_risk.tls.certresolver=letsencrypt"
      - "traefik.http.services.api_risk.loadbalancer.server.port=8000"


  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_autoscore
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_BASIC_AUTH_ACTIVE: "false"

      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: 172.19.0.2
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB_N8N}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

      GENERIC_TIMEZONE: America/New_York
      N8N_HOST: ${N8N_HOST}
      N8N_PROTOCOL: https
      N8N_PORT: 5678
      WEBHOOK_URL: https://${N8N_HOST}/

      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"

    volumes:
      - n8n_data:/home/node/.n8n

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${N8N_HOST}`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.docker.network=dokploy-network"

    networks:
      - autoscore_net
      - dokploy-network
    restart: always


networks:
  autoscore_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
  dokploy-network:
    external: true


volumes:
  postgres_data:
  api_risk_data:
  api_risk_models:
  api_risk_reports:
  api_risk_files:
  n8n_data: