services:

  postgres:
    image: postgres:15
    container_name: postgres_autoscore
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - autoscore_net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  api_risk:
    build: ./Apis/risk_score
    container_name: api_risk_score
    environment:
      URL_API_ZIDRA: ${URL_API_ZIDRA}
      USUARIO_ZIDRA: ${USUARIO_ZIDRA}
      PASSWORD_ZIDRA: ${PASSWORD_ZIDRA}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB_AUTOSCORE}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - autoscore_net
    restart: always


  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_autoscore
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - autoscore_net
      - dokploy-network
    restart: always


networks:
  autoscore_net:
    driver: bridge

  dokploy-network:
    external: true

volumes:
  postgres_data:
  api_risk_data:
  api_risk_models:
  api_risk_reports:
  api_risk_files:
  n8n_data:
